

# Create MYSQL PV

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
spec:
  storageClassName: "manual"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: node01
    # Exported path of your NFS server
    path: "/test"

---

# Create MYSQL PVC

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi

---

# Create MYSQL Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: docker.io/mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: redhat
        volumeMounts:
        - name: mysqlvol 
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqlvol
        persistentVolumeClaim:
          claimName: mysqlpvc
status: {}

---

# Create Service for MYSQL Deployment

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
status:
  loadBalancer: {}

---
